services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5434:5432 # enables connecting locally via psql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
