import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import { Providers } from "./providers";
import Header from "@/components/nav/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen relative flex flex-col justify-between w-full`}
      >
        <Providers>
          <Header />
          <main className=" flex-1 min-h-full">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
