import type { Metadata } from "next";

import "./globals.css";
import { Montserrat } from "next/font/google";
// import { Providers } from "./providers";

const montserrat = Montserrat({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body
        className={`  antialiased min-h-screen relative flex flex-col justify-between w-full`}
      >
        {/* <Providers> */}
        {/* <Header /> */}
        <main className=" flex-1 min-h-full">{children}</main>
        {/* <Footer /> */}
        {/* </Providers> */}
      </body>
    </html>
  );
}
